import type { NextPage } from 'next';
import Head from 'next/head';
import classNames from 'classnames';
import { useState } from 'react';
import { Button } from '../stories/Button';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [detailOpen, setDetailOpen] = useState(false);

  const toggleDetailContent = () => {
    setDetailOpen(!detailOpen);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button size="large" label="버튼" />
      </main>

      <ul className={styles.gnb}>
        <li>
          <a href="#">GNB1</a>
          <ul>
            <li>
              <a href="#">subMenu01</a>
            </li>
            <li>
              <a href="#">subMenu02</a>
            </li>
            <li>
              <a href="#">subMenu03</a>
            </li>
            <li>
              <a href="#">subMenu04</a>
            </li>
            <li>
              <a href="#">subMenu05</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#">GNB2</a>
          <ul>
            <li>
              <a href="#">subMenu11</a>
            </li>
            <li>
              <a href="#">subMenu12</a>
            </li>
            <li>
              <a href="#">subMenu13</a>
            </li>
            <li>
              <a href="#">subMenu14</a>
            </li>
            <li>
              <a href="#">subMenu15</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#">GNB3</a>
          <ul>
            <li>
              <a href="#">subMenu21</a>
            </li>
            <li>
              <a href="#">subMenu22</a>
            </li>
            <li>
              <a href="#">subMenu23</a>
            </li>
            <li>
              <a href="#">subMenu24</a>
            </li>
            <li>
              <a href="#">subMenu25</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#">GNB4</a>
          <ul>
            <li>
              <a href="#">subMenu31</a>
            </li>
            <li>
              <a href="#">subMenu32</a>
            </li>
            <li>
              <a href="#">subMenu33</a>
            </li>
            <li>
              <a href="#">subMenu34</a>
            </li>
            <li>
              <a href="#">subMenu35</a>
            </li>
          </ul>
        </li>
      </ul>

      <ul className={styles.radios}>
        <li>
          <label htmlFor="radio1">
            <input type="radio" name="radioText" id="radio1" value="123" /> 월 9만원
          </label>
        </li>
        <li>
          <label htmlFor="radio2">
            <input type="radio" name="radioText" id="radio2" value="123" /> 월 900만원
          </label>
        </li>
      </ul>

      <div className={styles.detailList}>
        <div className={classNames(styles.detailHeader, detailOpen && styles.open)}>
          <button type="button" onClick={toggleDetailContent}>
            자세한 라이선스 안내
          </button>
        </div>
        {detailOpen && (
          <div className={styles.detailContent}>
            <dl>
              <dt>문서/서식</dt>
              <dd>일반문서, 단체 내부문서, 홍보문서, 시험지, 교재</dd>
              <dt>문서/서식</dt>
              <dd>일반문서, 단체 내부문서, 홍보문서, 시험지, 교재</dd>
              <dt>문서/서식</dt>
              <dd>일반문서, 단체 내부문서, 홍보문서, 시험지, 교재</dd>
            </dl>
          </div>
        )}
      </div>
    </div>
  );
};

export default Home;
